Replace seed node listing with configuration to seed node HTTP API URl
cytechmobile/radicle-jetbrains-plugin pull request #210
Opened 2023-03-30 10:30 UTC by JChrist

Closes #203

2023-03-31 10:27 UTC, Stelios123 requested changes

2023-03-31 10:27 UTC, Stelios123 commented on src/main/java/network/radicle/jetbrains/radiclejetbrainsplugin/config/RadicleSettingsView.java
> +                !getSelectedNodeUrl().equals(this.settings.getSeedNodes().get(0).url);
`getSeedNodes()` return an empty array if the user fills something in the text field without starting with http
check `getSeedNodes()` function (`RadicleSettingsHandler.class`)

2023-04-03 05:18 UTC, JChrist commented on src/main/java/network/radicle/jetbrains/radiclejetbrainsplugin/config/RadicleSettingsView.java
> -        ApplicationManager.getApplication().executeOnPooledThread(() -> {
This is most probably remainder from changes after merging. Previously, all callers of `updateRadVersionLabel` were already executing in pooled thread.

2023-04-03 05:21 UTC, JChrist commented on src/main/java/network/radicle/jetbrains/radiclejetbrainsplugin/config/RadicleSettingsView.java
> +        seedNodeApiUrl.setText(this.settings.getSeedNodes().get(0).url);
good catch! Although, currently, there is no way for the list to become empty, it's a cheap check that could otherwise cause issues.

2023-04-03 05:22 UTC, JChrist commented on src/main/java/network/radicle/jetbrains/radiclejetbrainsplugin/providers/ProjectApi.java
> +            if (res.getStatusLine().getStatusCode() == 200) {
I've never encountered such a case, but, sure!

2023-04-03 07:32 UTC, Stelios123 approved these changes

2023-04-03 07:33 UTC, merged